# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache


cache:
  paths:
  - node_modules/
  - client/node_modules/


test:
  stage: test
  script:
    - npm install
    - npm test


  
pack:
  stage: deploy
  before_script:
    #- cd client
    - npm install
    #- cd ..
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$STAGING_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    #- ssh-add <(echo "$STAGING_PRIVATE_KEY")
    #- ssh -p22 mjr316@shell1.doc.ic.ac.uk "echo `whoami`"
    #- tar czf webapp02.tar.gz .
    - pwd
    #StrictHostKeyChecking=no
    - scp -r * mjr316@cloud-vm-45-8.doc.ic.ac.uk:/home/webapp-deploy/
    #- ssh mjr316@cloud-vm-45-8.doc.ic.ac.uk "cd ../webapp-deploy/ && bash -i -c \"npm install\""
    - ssh mjr316@cloud-vm-45-8.doc.ic.ac.uk "cd ../webapp-deploy/client/ && bash -i -c \"npm install\""
    #- ssh -p22 mjr316@shell1 "mv htdocs/wp-content/themes/live htdocs/wp-content/themes/_old && mv htdocs/wp-content/themes/_tmp htdocs/wp-content/themes/live"
    #- ssh -p22 mjr316@shell1 "rm -rf htdocs/wp-content/themes/_old"
  only:
    - master

